Detail screen styles applied
OntimizeWeb/ontimize-web-template-manager pull request #10
Opened 2024-05-21 13:05 UTC by javier-fernandez-imatia

2024-06-05 14:42 UTC, daniel-grana requested changes

2024-06-05 14:42 UTC, daniel-grana commented on src/app/main/home/detail/detail.component.ts
>          this.templateImg = response.data[0].IMG;
Comprobar que data[0] existe para que no salte excepción al intentar acceder

2024-06-05 14:42 UTC, daniel-grana commented on src/app/main/home/detail/detail.component.html
> +      <a href="https://github.com/OntimizeWeb" target="_blank">
por qué hacer esto así en vez de utilizar un o-buton con icon? Hay que tener en cuenta que después habrá que construir el link para redirigir a la carpeta del repositorio github en función de la template. Casi mejor asociar una función en el onClick y después construir el link en el controlador.

2024-06-05 16:28 UTC, daniel-grana requested changes

2024-06-05 16:28 UTC, daniel-grana commented on src/app/main/home/detail/detail-theme.scss
> +          box-shadow: 0px 4px 4px 0px #00000029;
¿por qué son diferentes los box-shadow si están en light o dark?

2024-06-05 16:44 UTC, patricia-martinez-imatia requested changes

2024-06-05 16:44 UTC, patricia-martinez-imatia commented on src/app/main/home/detail/detail.component.ts
> +    {
https://ontimizeweb.github.io/docs/v15/addons/gallery/component/overview#aspect-ratio-new
Yo usaria un ratio de 4:3 para que sea responsive

2024-06-05 17:03 UTC, patricia-martinez-imatia requested changes
1. Boton de volver tiene que estar alineado con el titulo
![image](https://github.com/OntimizeWeb/ontimize-web-template-manager/assets/32088627/41fcf5b5-3cfd-4371-a73d-a20668818d67)
2. La parte de izquierda debe estar fija a la hora de hacer scroll
3. El padding entre los titulos de las secciones y la descripcion no se corresponde con el diseño
4. Estan saliendo errores por consola
![image](https://github.com/OntimizeWeb/ontimize-web-template-manager/assets/32088627/c1037389-a6d4-48a1-a077-3d4d1dfae4fc)

2024-06-05 17:03 UTC, patricia-martinez-imatia commented on src/app/main/home/detail/detail-theme.scss
> +  $accent: map-get($theme, color, accent);
```suggestion
```

2024-06-05 17:03 UTC, patricia-martinez-imatia commented on src/app/main/home/detail/detail-theme.scss
> +  $warn: map-get($theme, color, warn);
```suggestion
```

2024-06-05 17:03 UTC, patricia-martinez-imatia commented on src/app/main/home/detail/detail-theme.scss
> +  $typography: map-get($theme, typography);
```suggestion
```

2024-06-07 10:24 UTC, tomfacal commented on src/app/main/home/detail/detail.component.scss
> +    align-items: start;
No te sale un warning por este start?

2024-06-10 15:02 UTC, patricia-martinez-imatia requested changes
- [x] Scroll pegado a la derecha en toda la pagina

![image](https://github.com/OntimizeWeb/ontimize-web-template-manager/assets/32088627/7c24ae3b-470a-4267-9732-36d7f3d34f23)

2024-06-11 08:02 UTC, patricia-martinez-imatia approved these changes

2024-06-11 08:03 UTC, merged