Home screen changes applied
OntimizeWeb/ontimize-web-template-manager pull request #8
Opened 2024-05-14 12:57 UTC by javier-fernandez-imatia

2024-05-27 11:45 UTC, javier-fernandez-imatia commented on src/assets/dummy-data/templates-data.json
> +      "IMG": "../../assets/images/template-images/template4.png",
El campo IMAGES lo voy a añadir en la PR de la pantalla detail.

2024-05-27 17:04 UTC, patricia-martinez-imatia requested changes

2024-05-27 17:04 UTC, patricia-martinez-imatia commented on src/assets/images/open_detail_dark.png
this icon is in https://fonts.google.com/icons?selected=Material+Symbols+Outlined:open_in_new:FILL@0;wght@400;GRAD@0;opsz@24&icon.query=new&icon.size=24&icon.color=%23e8eaed

2024-05-29 07:11 UTC, patricia-martinez-imatia requested changes
![image](https://github.com/OntimizeWeb/ontimize-web-template-manager/assets/32088627/a9ee8762-2795-40ac-ab90-eb370d01c985)
1. Filter templates no puede mostrarse en dos lineas y deberia estar en negrita, completar el estilo del boton clear
2. El scroll de los filtros deberia empezar despues de filter templates
3. Ajustar el numero de templates por columna segun la resolucion de la pantalla al menos hasta 1280px de ancho
4. Solo mostrar dos lineas de descripcion, si hay mas contenido mostrar ellipsis y tooltip

2024-05-29 12:41 UTC, patricia-martinez-imatia requested changes

2024-05-29 12:41 UTC, patricia-martinez-imatia commented on src/app/main/main.component.html
> +  <img src="../../../../assets/images/ontimize_web_log.png" alt="Ontimize logo" height="40px" width="138px">
```suggestion
  <img src="assets/images/ontimize_web_log.png" alt="Ontimize logo" height="40px" width="138px">
```

2024-05-30 10:18 UTC, patricia-martinez-imatia requested changes
- Quitar las clases de angular de los estilso como ng-star-inserted

2024-05-30 10:18 UTC, patricia-martinez-imatia commented on src/styles.scss
> +mat-grid-tile.mat-grid-tile.ng-star-inserted {
Esta clase tiene que ir para el scss de la home

2024-05-30 10:23 UTC, patricia-martinez-imatia requested changes

2024-05-30 10:23 UTC, patricia-martinez-imatia commented on src/app/main/home/home.component.ts
> +    this.subscription.add(this.media.asObservable().subscribe((change: MediaChange[]) => {
Desuscribir cuando se destruye el componente

2024-05-31 08:25 UTC, daniel-grana approved these changes

2024-05-31 08:25 UTC, merged